---
title: "Module 4 Quiz"
author: "®γσ, Eng Lian Hu"
date: "July 22, 2016"
output: word_document
---

Module 4 Quiz

15 questions

*Correct*
*1 / 1 points*
1. Consider the following situation in which firm A acquires firm B in a one-for-one stock deal:

Firm A	Firm B	Merged Firm
Earnings	120	120	230
# shares	100	50	150
Price/share	30	30	
EPS	1.2	2.4	1.53
Is the following statement true or false?

  Despite the positive impact of the merger on the acquirer’s EPS (earnings-per-share), this acquisition is probably bad for the shareholders of the acquirer because it has a negative effect on total profits.

- **True**
- False

1 points
2. A CFO is considering an acquisition of a target that is currently worth 3 billion dollars. The acquisition will produce annual after-tax cost savings of 70 million dollars. This annual cost savings is expected to begin in two years and to grow at the rate of inflation (assume it is 1%). In addition, the CFO expects that the acquisition will create an after-tax integration cost of 250 million dollars. Assume the integration cost will occur one year from now. The current discount rate of the acquirer is 10%.

The NPV of the synergies associated with this acquisition is _________.

- 480 million
- 420 million
- **725 million**
- 545 million

1 points
3. A CFO is considering an acquisition of a target that is currently worth 3 billion dollars. The acquisition will produce annual after-tax cost savings of 70 million dollars. This annual cost savings is expected to begin in two years and to grow at the rate of inflation (assume it is 1%). In addition, the CFO expects that the acquisition will create an after-tax integration cost of 250 million dollars. Assume the integration cost will occur one year from now. The current discount rate of the acquirer is 10%.

Which of the following values would not be a reasonable price to offer to the target?

- 3.25 billion
- **3.3 billion**
- 3.1 billion
- 2.9 billion

1 points
4. A company that has equity value of 75 billion dollars is proposing an acquisition of a competitor in the same industry whose equity is worth 41 billion dollars. The synergies associated with the merger have been estimated to be equal to 9 billion dollars.

How much should the acquirer pay for the target in this case?

- Between 41 and 75 billion dollars
- **Whatever is necessary to get the deal done.**
- Less than 41 billion dollars
- Between 41 and 50 billion dollars

1 points
5. A company that has equity value of 75 billion dollars is proposing an acquisition of a competitor in the same industry whose equity is worth 41 billion dollars. The synergies associated with the merger have been estimated to be equal to 9 billion dollars.

  Suppose that the acquirer has 4 billion shares outstanding, and the target has 5 billion shares outstanding. Assume that the acquirer is paying 50 billion for the equity of the target and that the acquirer stock price will stay at 18.75 dollars a share. What should be the exchange ratio for this merger in a stock deal?

- 0.44 shares of the acquirer for each target share
- 0.53 shares of the acquirer for each target share
- **1 share of the acquirer for each target share**
- 1.875 shares of the acquirer for each target share

1 point
6. Almeida and partners (a private equity firm) is considering a LBO of Example Inc.,which has an equity value of 10B dollars. Example Inc. requires a 20% premium to complete the deal. Almeida and partners has 1.5B in cash to finance the deal and is planning to finance the rest with a new bank loan. The plan is to buy 100% of the shares of Example Inc. and take it private. Almeida and partners will assume all the existing debt of Example Inc. (existing debt is equal to 2B). Example Inc. has no cash in its balance sheet.

The new bank loan that Almeida and partners needs to complete this deal is equal to _______________.

- 12 billion
- **9 billion**
- 10.5 billion
- 10 billion

1 points
7. Consider the example of sensitivity analysis that we discussed in class (in the spreadsheet Sensitivity.xls).

  What happens to the NPV and the IRR of the project when the cost per unit goes from 0.8 to 2 dollars?

- The IRR is unchanged, and the NPV goes to $-1,235.
- The IRR goes to 5.7%, and the NPV goes to $-3,756.
- **The IRR goes to 7.2%, and the NPV goes to $-3,756.**
- The IRR goes to 7.2%, and the NPV goes to $-1,235.

*Correct*
*1 / 1 points*
8. Is the following statement true or false? If there is a 10% chance that the cost per unit will be equal to 2 dollars, you should reject the project because there is a significant chance that the NPV will be negative.

- True
- **False**

*Correct*
*1 / 1 points*
9. Suppose a company has a required return on equity equal to 9%. Calculate the company’s Beta if the 30-year government bond yield is 3% and the market risk premium is 5%.

- 1
- **1.2**
- 1.4
- 0.83

1 points
10. Your company’s required return on debt is 6%, its tax rate is 30%, and its required return on equity is 10%. The company has 20 billion dollars of debt, and book equity is 10 billion dollars. The stock price is 10 dollars a share, and the company has 5 billion shares outstanding. The company’s WACC is _________.

- You don't have sufficient information to estimate WACC.
- 9.3%
- **7.1%**
- 8.3%

1 points
11. Consider the following data. The figures are in millions of dollars.

Balance sheet

Cash	3000	Current liabilities	5000
Other current assets	7000	Long-term debt	25000
Non-current assets	50000	Equity	30000
Income statement

Operating income	6000
Interest payment	2500
Income before taxes	3500
Taxes	1050
Net income	2450
The company's OPAT is equal to ________.

- 6,000
- **3,500**
- 4,950
- 2,450

1 points
12. Consider the following data. The figures are in millions of dollars.

Balance sheet

Cash	3000	Current liabilities	5000
Other current assets	7000	Long-term debt	25000
Non-current assets	50000	Equity	30000
Income statement

Operating income	6000
Interest payment	2500
Income before taxes	3500
Taxes	1050
Net income	2450
The company's operating assets are equal to __________.

- 50,000
- 30,000
- **60,000**
- 57,000

1 points
13. Consider the following data. The figures are in millions of dollars.

Balance sheet

Cash	3000	Current liabilities	5000
Other current assets	7000	Long-term debt	25000
Non-current assets	50000	Equity	30000
Income statement

Operating income	6000
Interest payment	2500
Income before taxes	3500
Taxes	1050
Net income	2450
If the required return on debt is 5%, the required return on equity is 12%, and the market value of equity is 80 billion dollars, the WACC is _________.

- 11.5%
- 12%
- **9.5%**
- 10%

1 points
14. Consider the following data. The figures are in millions of dollars.

Balance sheet

Cash	3000	Current liabilities	5000
Other current assets	7000	Long-term debt	25000
Non-current assets	50000	Equity	30000
Income statement

Operating income	6000
Interest payment	2500
Income before taxes	3500
Taxes	1050
Net income	2450
EVA (economic value added) is equal to _________.

- -564
- -750
- **729**
- 325

*Correct*
*1 / 1 points*
15. Is the following statement true or false?

  The negative EVA shows that the company did not generate economic profits this year. However, there is no need to restructure operations if the EVA is expected to become positive in future years.

- **True**
- False
